### ISSUE TITLE
小部件字体很大

### ISSUE THREAD

**Issue by chenkeao** [GideonSenku/Scriptable#22]
ios14桌面小部件字体很大，显示的不完整

**Comment by xfoxtbat** [comment]
一样的困扰
![image](https://user-images.githubusercontent.com/18201918/93693886-39855080-fb38-11ea-9a7e-66f7e55ccc48.png) 想实现图片 字体大小 请教怎么设置

**Comment by chenkeao** [comment]
> 一样的困扰
> ![image](https://user-images.githubusercontent.com/18201918/93693886-39855080-fb38-11ea-9a7e-66f7e55ccc48.png) 想实现图片 字体大小 请教怎么设置

我看到代码里有font.Size的属性，但是改了也不生效。并且最后会执行更新代码，把手动修改的给覆盖掉

**Comment by GideonSenku** [comment]
设计如此，建议用中的大小，再大也显示不了全部的内容

发自我的iPhone

**Comment by chenkeao** [comment]
> 设计如此，建议用中的大小，再大也显示不了全部的内容 发自我的iPhone
> […](#)

![0D04C4E0-DAC0-4DA8-88F6-F9625B64187D](https://user-images.githubusercontent.com/61346279/93705419-be2f9900-fb4f-11ea-8bc7-125e9fe30949.png)
这是我的显示效果，基本不能看...

**Comment by GideonSenku** [comment]
> > 设计如此，建议用中的大小，再大也显示不了全部的内容 发自我的iPhone
> > […](#)
> 
> ![0D04C4E0-DAC0-4DA8-88F6-F9625B64187D](https://user-images.githubusercontent.com/61346279/93705419-be2f9900-fb4f-11ea-8bc7-125e9fe30949.png)
> 这是我的显示效果，基本不能看...

@evilbutcher 大佬看看

**Comment by evilbutcher** [comment]
> > > 设计如此，建议用中的大小，再大也显示不了全部的内容 发自我的iPhone
> > > […](#)
> > 
> > 
> > ![0D04C4E0-DAC0-4DA8-88F6-F9625B64187D](https://user-images.githubusercontent.com/61346279/93705419-be2f9900-fb4f-11ea-8bc7-125e9fe30949.png)
> > 这是我的显示效果，基本不能看...
> 
> @evilbutcher 大佬看看

emmmm我复现不出来，暂时还不知道是什么问题（捂脸

**Comment by evilbutcher** [comment]
> ios14桌面小部件字体很大，显示的不完整

加tf即可：https://testflight.apple.com/join/uN1vTqxk

**Comment by chenkeao** [comment]
> > ios14桌面小部件字体很大，显示的不完整
> 
> 加tf即可：https://testflight.apple.com/join/uN1vTqxk

感谢

**Comment by ddu7** [comment]
有个更简单的方法。从Documents看ListWidget使用addText()会生成WidgetText，用Font方法可以控制字体大小。
略修改addTextToListWidget这个函数即可：
```
function addTextToListWidget(text, listWidget) {
  let item = listWidget.addText(text);
  if (rancolor == true) {
    item.textColor = new Color(color16());
  } else {
    item.textColor = Color.white();
  }
  // item.textSize = 12;
  item.font = new Font('SF Mono', 14);
}
```
把`item.textSize = 12;`改成用font，`item.font = new Font('SF Mono', 14)`，第一个参数选择字体，第二个参数改动字体大小。

**Comment by evilbutcher** [comment]
> 我也有这个问题，读了文档接口找到一个更简单的方法。从Documents看ListWidget使用addText()会生成WidgetText，定义font属性可以控制字体大小。
> 略修改addTextToListWidget这个函数即可：
> 
> ```
> function addTextToListWidget(text, listWidget) {
>   let item = listWidget.addText(text);
>   if (rancolor == true) {
>     item.textColor = new Color(color16());
>   } else {
>     item.textColor = Color.white();
>   }
>   // item.textSize = 12;
>   item.font = new Font('SF Mono', 14);
> }
> ```
> 
> 把`item.textSize = 12;`改成用font，`item.font = new Font('SF Mono', 14)`，第一个参数选择字体，第二个参数改动字体大小。
> 手头只有11 pro，不知道这个会不会对不同尺寸屏幕产生适配问题。。。

我有空试试看
