### ISSUE TITLE
rssmonitor监控的链接如何更改？

### ISSUE THREAD

**Issue by psterman** [GideonSenku/Scriptable#25]
你好！
我要将rssmonitor监控的页面修改成https://rsshub.app/zaobao/realtime/china
但是我在脚本里找到两个修改位置都没有效果，提示格式不正确，请问要如何修改？

**Comment by GideonSenku** [comment]
> 你好！
> 我要将rssmonitor监控的页面修改成https://rsshub.app/zaobao/realtime/china
> 但是我在脚本里找到两个修改位置都没有效果，提示格式不正确，请问要如何修改？

// Fill in the RSS subscription link, the default is the latest Commit of the Repo
var rsslink = "https://github.com/GideonSenku/Scriptable/commits/master.atom";

**Comment by psterman** [comment]
fill this？
var rsslink = "https://rsshub.app/zaobao/realtime/china";

**Comment by psterman** [comment]
我修改了无效，是不是要把env.js里的js代码也要相应调整？

**Comment by evilbutcher** [comment]
> 我修改了无效，是不是要把env.js里的js代码也要相应调整？

关掉自动更新或者利用config，参见 https://github.com/evilbutcher/Scriptables/blob/master/README.md

**Comment by psterman** [comment]
谢谢，弄好了！也理解了！
