### ISSUE TITLE
小部件字体样式过大

### ISSUE THREAD

**Issue by 52znn** [GideonSenku/Scriptable#27]
设置好之后桌面添加最小的部件 字体很大会超出边框 请问怎么修改？http://tu.yaohuo.me/imgs/2020/09/564e5a57e061abe4.jpeg

**Comment by evilbutcher** [comment]
> 设置好之后桌面添加最小的部件 字体很大会超出边框 请问怎么修改？http://tu.yaohuo.me/imgs/2020/09/564e5a57e061abe4.jpeg

等G大merge就好
