### ISSUE TITLE
豆瓣微博B站const goupdate = true; 需要提取配置，弄成可配置不要自动更新

### ISSUE THREAD

**Issue by mr-dragon** [GideonSenku/Scriptable#30]
**没必要每次都更新，要么一天一次要么可配置，一般最少好几天才会更新一次吧，稳定的话可能一个月都不更新，这样会慢的，网络io啥的都浪费了。**

而且频率太高好像有个https的报错（偶发之前遇到过，可能是更新数据的 URL 限制的，不是更新github脚本文件引发的）

**Comment by GideonSenku** [comment]
改成false

**Comment by mr-dragon** [comment]
> 改成false

知道，就是觉得需要统一管理，手动改也行，我直接注释了更新的update方法了
