### ISSUE TITLE
Widget isn‘t working

### ISSUE THREAD

**Issue by serverpaul** [GideonSenku/Scriptable#33]
I added the Widget to the Homescreen and selected "Run Script". But it only shows the standard screen and when I toch it, it opens the app and shows me the Widget there. ![image](https://user-images.githubusercontent.com/73078650/97118664-8944d200-170b-11eb-83f6-d140dc8a5e10.png)![image](https://user-images.githubusercontent.com/73078650/97118667-8d70ef80-170b-11eb-8ba2-2d1d75d11851.png)![image](https://user-images.githubusercontent.com/73078650/97118669-8f3ab300-170b-11eb-8d92-543836cdf13a.png)

**Comment by GideonSenku** [comment]
Maybe system memory over limted
